"""
Configuration package for the x2telegram application.
"""

from .constants import (
    # Timeouts
    DEFAULT_HTTP_TIMEOUT,
    IMAGE_DOWNLOAD_TIMEOUT,
    TELEGRAM_TIMEOUT,
    OLLAMA_TIMEOUT,
    CLAUDE_TIMEOUT,
    OPENAI_TIMEOUT,
    GEMINI_TIMEOUT,
    RSS_TIMEOUT,
    # Retry configuration
    DEFAULT_MAX_RETRIES,
    DEFAULT_RETRY_DELAY,
    DEFAULT_BACKOFF_FACTOR,
    RSS_MAX_RETRIES,
    RETRY_JITTER_MIN,
    RETRY_JITTER_MAX,
    # Rate limiting
    TELEGRAM_RATE_LIMIT,
    RSS_RATE_LIMIT_WAIT,
    # AI parameters
    AI_MAX_TOKENS,
    AI_TEMPERATURE,
    AI_CONFIDENCE_THRESHOLD,
    # Processing
    DEFAULT_MAX_WORKERS,
    DEFAULT_PENDING_LIMIT,
    SEQUENTIAL_PROCESSING_DELAY,
    # HTML parsing
    DOM_TRAVERSAL_MAX_LEVELS,
    # API versions
    CLAUDE_API_VERSION,
    # API endpoints
    TELEGRAM_API_BASE,
    CLAUDE_API_ENDPOINT,
    GEMINI_API_BASE,
)

from .settings import (
    # Paths
    ROOT_DIR,
    DATA_DIR,
    DATABASE_PATH,
    # Telegram
    TELEGRAM_BOT_TOKEN,
    TELEGRAM_CHAT_ID,
    # AI Provider
    AI_PROVIDER,
    AI_PROMPT,
    # Ollama
    OLLAMA_URL,
    OLLAMA_MODEL,
    OLLAMA_PROMPT,
    # Claude
    CLAUDE_API_KEY,
    CLAUDE_MODEL,
    CLAUDE_PROMPT,
    # OpenAI
    OPENAI_API_KEY,
    OPENAI_MODEL,
    OPENAI_BASE_URL,
    OPENAI_PROMPT,
    # DeepSeek
    DEEPSEEK_API_KEY,
    DEEPSEEK_MODEL,
    DEEPSEEK_BASE_URL,
    DEEPSEEK_PROMPT,
    # Gemini
    GEMINI_API_KEY,
    GEMINI_MODEL,
    GEMINI_PROMPT,
    # Processing
    MAX_TWEETS_PER_USER,
    NITTER_MIRRORS,
    # Filtering
    FILTER_KEYWORDS_INCLUDE,
    FILTER_KEYWORDS_EXCLUDE,
    FILTER_REGEX_INCLUDE,
    FILTER_REGEX_EXCLUDE,
)